services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: take-give-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: take_give_db
      MYSQL_USER: take_give_user
      MYSQL_PASSWORD: take_give_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - take-give-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  # Backend API Server
  backend:
    build: ./backend
    container_name: take-give-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=take_give_user
      - DB_PASSWORD=take_give_password
      - DB_NAME=take_give_db
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - PORT=3000
    depends_on:
      - mysql
    networks:
      - take-give-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Login Page Frontend
  frontend:
    image: nginx:alpine
    container_name: take-give-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./loginPage:/usr/share/nginx/html/loginPage
      - ./menuPage:/usr/share/nginx/html/menuPage
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - take-give-network

  # phpMyAdmin (Optional - for database management)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: take-give-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - take-give-network

volumes:
  mysql_data:
    driver: local

networks:
  take-give-network:
    driver: bridge
